#!/usr/bin/env python3
"""
将 AEpy 项目文件编码为 C 头文件 (embedded_files.h)，供安装器编译使用。
用法：python tools/embed_files.py
"""
import os

# tools/embed_files.py -> tools -> 项目根目录
TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(TOOLS_DIR)
OUTPUT = os.path.join(TOOLS_DIR, "embedded_files.h")

# 不参与嵌入的目录/文件（虚拟环境、构建产物、开发脚本等）
EXCLUDE = {
    ".venv",
    "venv",
    "env",
    "__pycache__",
    "tools",
    ".git",
    "launcher.c",
    "launcher.rc",
    "app.manifest",
    "build_launcher.bat",
    "embedded_files.h",
    "AEpy.md",
    ".gitignore",
}

files = []
for root, dirs, fnames in os.walk(PROJECT_ROOT):
    dirs[:] = [d for d in dirs if d not in EXCLUDE]
    for f in fnames:
        if f in EXCLUDE or f.lower().endswith((".o", ".obj", ".exe", ".pyc")):
            continue
        full = os.path.join(root, f)
        rel = os.path.relpath(full, PROJECT_ROOT)
        files.append((rel, full))

files.sort(key=lambda x: x[0])

with open(OUTPUT, "w", encoding="utf-8") as h:
    h.write("/* Auto-generated by embed_files.py - DO NOT EDIT */\n")
    h.write("#ifndef EMBEDDED_FILES_H\n#define EMBEDDED_FILES_H\n\n")

    for idx, (rel_path, full_path) in enumerate(files):
        with open(full_path, "rb") as f:
            data = f.read()
        h.write(f"/* {rel_path} ({len(data)} bytes) */\n")
        h.write(f"static const unsigned char file_{idx}[] = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            parts = [f"0x{b:02x}" for b in chunk]
            h.write(f"    {', '.join(parts)},\n")
        h.write("};\n\n")

    count = len(files)
    h.write(f"#define EMBEDDED_FILE_COUNT {count}\n\n")
    h.write("typedef struct {\n")
    h.write("    const char *rel_path;\n")
    h.write("    const unsigned char *data;\n")
    h.write("    unsigned int size;\n")
    h.write("} EmbeddedFile;\n\n")
    h.write("static const EmbeddedFile embedded_files[] = {\n")
    for idx, (rel_path, full_path) in enumerate(files):
        c_path = rel_path.replace("\\", "/")
        size = os.path.getsize(full_path)
        h.write(f'    {{"{c_path}", file_{idx}, {size}}},\n')
    h.write("};\n\n")
    h.write("#endif /* EMBEDDED_FILES_H */\n")

print(f"生成 {OUTPUT}")
print(f"共 {count} 个文件嵌入")
total_size = sum(os.path.getsize(f) for _, f in files)
print(f"总大小: {total_size} 字节 ({total_size/1024:.1f} KB)")
